// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPlo5X7J3VYapEKZd6NO9-ZGIvTRfAvq8',
    appId: '1:156281058832:web:df0f8af766b4508b3bfc95',
    messagingSenderId: '156281058832',
    projectId: 'resultresolve-817a2',
    authDomain: 'resultresolve-817a2.firebaseapp.com',
    storageBucket: 'resultresolve-817a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB067_l6LKtD8YjJudNgYg3KWR8T3z2WJk',
    appId: '1:156281058832:android:d1a5ee2adca9ff043bfc95',
    messagingSenderId: '156281058832',
    projectId: 'resultresolve-817a2',
    storageBucket: 'resultresolve-817a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn14T9yOfC-urYhtlQ2qN5HVaPdzaH-4o',
    appId: '1:156281058832:ios:8f1d8a9eac9dbe203bfc95',
    messagingSenderId: '156281058832',
    projectId: 'resultresolve-817a2',
    storageBucket: 'resultresolve-817a2.appspot.com',
    iosBundleId: 'com.example.resultresolve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn14T9yOfC-urYhtlQ2qN5HVaPdzaH-4o',
    appId: '1:156281058832:ios:8f1d8a9eac9dbe203bfc95',
    messagingSenderId: '156281058832',
    projectId: 'resultresolve-817a2',
    storageBucket: 'resultresolve-817a2.appspot.com',
    iosBundleId: 'com.example.resultresolve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPlo5X7J3VYapEKZd6NO9-ZGIvTRfAvq8',
    appId: '1:156281058832:web:7d5782cc666a7d893bfc95',
    messagingSenderId: '156281058832',
    projectId: 'resultresolve-817a2',
    authDomain: 'resultresolve-817a2.firebaseapp.com',
    storageBucket: 'resultresolve-817a2.appspot.com',
  );
}
